<template>
  <aside class="panel situation-panel">
    <section class="situation-section"><div class="section-head"><div><span class="eyebrow">SELECTED ELEMENT</span><h2>单位状态与决策链</h2></div></div><div id="unitDetail" class="unit-detail"><div class="empty-detail">从左侧选择单位</div></div></section>
    <section class="situation-section"><div class="section-head"><h3>附近资源点</h3><span class="resource-note">余量由协议隐藏</span></div><div id="resourceInfo" class="resource-list muted">当前无可见资源点</div></section>
    <section class="situation-section"><h3>目标与任务概览</h3><div id="goals" class="compact-list muted">尚无决策记录</div><div id="tasks" class="compact-list muted"></div></section>
    <details class="order-drawer" open><summary>人工任务 · 地图下令</summary><div class="detail-actions"><p class="muted">只对选中对象生效，下一权威 Tick 会重新校验。</p><div class="auth-row"><input id="password" type="password" autocomplete="current-password" placeholder="管理员口令"><button id="login" class="neutral">认证</button></div><span id="loginState" class="muted" aria-live="polite"></span><div class="task-form"><label for="taskAlias">对象</label><select id="taskAlias"><option value="">选择当前实体…</option></select><label for="taskKind">任务</label><select id="taskKind"><option value="HOLD_POSITION">原地待命</option><option value="RETREAT_TO_CORE">撤回核心</option><option value="HARVEST_VISIBLE">采集可见资源</option><option value="MOVE_TO_CELL">移动到目标</option></select><label for="taskPriority">优先级</label><select id="taskPriority"><option value="500">普通 · 500</option><option value="800" selected>高 · 800</option><option value="950">紧急 · 950</option></select><label for="taskTarget">目标坐标</label><input id="taskTarget" inputmode="numeric" placeholder="x,y（仅移动）"><button id="assign" class="primary-action">排队任务</button></div><p id="taskState" class="muted" aria-live="polite"></p><div id="taskCommands" class="command-list muted">认证后显示人工任务。</div></div></details>
    <details class="advanced-drawer"><summary>策略与指挥设置</summary><div class="advanced-grid"><section><h3>核心迁移</h3><input id="migrationTarget" placeholder="目标 x,y"><div class="button-row"><button id="migrate" class="neutral">排队迁移</button><button id="cancelMigration" class="neutral">取消</button></div></section><section><h3>策略姿态</h3><p class="muted">生效：<span id="policyCurrent">均衡</span></p><select id="policyPosture"><option value="BALANCED">均衡</option><option value="DEFENSIVE">防御</option><option value="ECONOMY">经济</option><option value="AGGRESSIVE">进攻</option></select><button id="setPolicy" class="neutral">排队策略</button><p id="policyState" class="muted">认证后可更新。</p></section><section><h3>策略参数热更新</h3><div id="policyConfig" class="config-list muted">加载中…</div></section></div><h3>迁移分析</h3><div id="migrationAnalysis" class="compact-list muted">尚无迁移分析数据</div><div class="button-row"><button id="triggerAnalysis" class="neutral">立即扫描</button></div><p id="migrationState" class="muted"></p><h3>矿区饱和度</h3><div id="chunkSaturation" class="compact-list muted">尚无已知矿区</div><h3>命令审计</h3><div id="commands" class="compact-list muted">尚无命令</div><h3>任务切换</h3><div id="timeline" class="compact-list muted">尚无任务切换记录</div></details>
  </aside>
</template>
