<script setup lang="ts">
import { computed, ref } from 'vue'
import { useDashboardStore } from '../state/dashboard'
import { useTacticalMap } from '../map/useTacticalMap'

const dashboard = useDashboardStore()
const viewport = ref<HTMLElement | null>(null)
const map = useTacticalMap(viewport, dashboard)
const current = computed(() => dashboard.displayView.value?.current)
const summary = computed(() => `己方 ${current.value?.map?.friendly?.length || 0} · 敌方 ${current.value?.map?.enemies?.length || 0} · 资源 ${current.value?.map?.resources?.length || 0} · 已观测 ${current.value?.map?.observed?.length || 0}格`)
const modeLabel = computed(() => dashboard.replayLive.value ? '实时态势' : '历史回放')
function zoom(factor: number) { dashboard.mapRequest.value = { id: Date.now(), kind: 'zoom', factor } }
function reset() { dashboard.mapRequest.value = { id: Date.now(), kind: 'reset' } }
</script>

<template>
  <section class="map-panel" aria-label="战术地图工作区"><div class="map-heading"><div><span class="eyebrow">LIVE BATTLESPACE / GRID CONTROL</span><h2>战术地图</h2></div><div class="map-status"><span id="mapModeBadge" class="tag" :class="{ 'is-replay': !dashboard.replayLive.value }">{{ modeLabel }}</span><span id="mapSummary">{{ summary }}</span><span id="rendererStatus">{{ map.ready.value ? 'Pixi WebGL · 按需渲染' : '渲染器待命' }}</span></div></div><div class="map-toolbar" aria-label="地图控件"><div class="tool-group"><button id="mapZoomIn" class="map-tool" title="放大" @click="zoom(1.2)">＋</button><button id="mapZoomOut" class="map-tool" title="缩小" @click="zoom(.84)">－</button><button id="mapReset" class="map-tool" title="重置视口" @click="reset">归中</button></div><label class="layer-toggle"><input id="layerFog" v-model="map.fog.value" type="checkbox" @change="map.setLayer('fog', map.fog.value)"> 迷雾</label><label class="layer-toggle">视野 <select id="visionMode" v-model="map.vision.value" aria-label="视野显示模式" @change="map.setLayer('vision', map.vision.value)"><option value="selected">选中 + 核心</option><option value="all">全部单位</option><option value="off">关闭</option></select></label><label class="layer-toggle"><input id="layerCoordinates" v-model="map.coordinates.value" type="checkbox" @change="map.setLayer('coordinates', map.coordinates.value)"> 边尺</label><label class="layer-toggle"><input id="layerLabels" v-model="map.labels.value" type="checkbox" @change="map.setLayer('labels', map.labels.value)"> 标注</label><span class="map-legend"><i class="legend-unit worker"></i>工人 <i class="legend-unit vanguard"></i>先锋 <i class="legend-unit ranger"></i>游侠 <i class="legend-resource"></i>资源</span><button id="mapPickTarget" class="neutral map-order" :class="{ 'is-active': map.targetMode.value }" :aria-pressed="map.targetMode.value" @click="map.toggleTargetMode">地图选点下令</button></div><div id="map-viewport" ref="viewport" class="map" role="application" tabindex="0" aria-label="战术地图；拖拽平移，滚轮缩放，方向键移动视口"><div id="map-stage" class="map-stage"><div class="map-loading">正在初始化战术态势渲染器…</div></div><div id="map-axis-x" class="map-axis map-axis-x" aria-hidden="true"></div><div id="map-axis-y" class="map-axis map-axis-y" aria-hidden="true"></div><div class="map-reticle" aria-hidden="true"></div><div class="map-coordinate-strip"><span id="mapCenterCoordinate">中心 —</span><span id="mapCursor">光标 —</span><span id="mapSelectionCoordinate">选中 —</span><span id="mapTargetCoordinate">目标 —</span></div><div id="mapTargetMode" class="map-target-mode" :hidden="!map.targetMode.value">选点下单 · 移动光标预览路径 · 单击锁定目标</div><div id="mapRendererState" class="map-renderer-state" hidden></div><pre id="mapDebugHud" class="map-debug-hud" hidden></pre></div></section>
</template>
