/* PixiJS WebGL retained scene renderer. */
(() => {
  'use strict';
  const T = window.TacticalMap = window.TacticalMap || {};
  const { FLAGS, COLOR_NUMBERS, KIND_LABELS, KIND_HP, LIMITS, clamp, isCell, visibleBounds } = T;
  const inside = (cell, bounds, padding = 0) => cell[0] >= bounds.minX - padding && cell[0] <= bounds.maxX + padding && cell[1] >= bounds.minY - padding && cell[1] <= bounds.maxY + padding;
  T.isInBounds = inside;
  const notice = (state, message, { blocking = false, error = false } = {}) => { const status = state.byId('rendererStatus'), node = state.byId('mapRendererState'); if (status) { status.textContent = message; status.classList.toggle('is-error', error); } if (node) { node.hidden = !blocking; node.textContent = message; node.classList.toggle('is-error', error); } };
  const textureSet = state => {
    for (const kind of ['CORE', 'WORKER', 'VANGUARD', 'RANGER']) { const g = new PIXI.Graphics(); g.lineStyle(2, 0xffffff, 1); g.beginFill(0xffffff, kind === 'CORE' ? .28 : 1); if (kind === 'CORE') g.drawCircle(16, 16, 10); else if (kind === 'WORKER') g.drawRect(7, 7, 18, 18); else if (kind === 'VANGUARD') g.drawPolygon([16, 4, 28, 16, 16, 28, 4, 16]); else g.drawPolygon([16, 5, 27, 25, 5, 25]); g.endFill(); state.symbolTextures.set(kind, state.pixiApp.renderer.generateTexture(g, { region: new PIXI.Rectangle(0, 0, 32, 32), resolution: Math.min(2, window.devicePixelRatio || 1) })); g.destroy(); }
  };
  const initPixi = state => {
    if (!window.PIXI || (PIXI.utils?.isWebGLSupported && !PIXI.utils.isWebGLSupported())) { notice(state, 'WebGL 不可用 · 浏览器不支持', { blocking: true, error: true }); return false; }
    try {
      state.pixiApp = new PIXI.Application({ width: state.size.w, height: state.size.h, backgroundColor: COLOR_NUMBERS.bg, antialias: false, resolution: Math.min(1.5, window.devicePixelRatio || 1), autoDensity: true, autoStart: false, sharedTicker: false }); state.pixiApp.stop(); state.canvas = state.pixiApp.view || state.pixiApp.canvas; state.canvas.className = 'map-canvas'; state.canvas.setAttribute('aria-label', '当前战术地图（Pixi WebGL 按需渲染）'); state.stageHost.replaceChildren(state.canvas);
      state.surfaceGraphic = new PIXI.Graphics(); state.pixiWorld = new PIXI.Container(); state.observedGraphic = new PIXI.Graphics(); state.gridGraphic = new PIXI.Graphics(); state.terrainGraphic = new PIXI.Graphics(); state.visionGraphic = new PIXI.Graphics(); state.pathGraphic = new PIXI.Graphics(); state.unitLayer = new PIXI.Container(); state.radarLayer = new PIXI.Container(); state.pixiWorld.addChild(state.observedGraphic, state.gridGraphic, state.terrainGraphic, state.visionGraphic, state.pathGraphic, state.unitLayer); state.pixiApp.stage.addChild(state.surfaceGraphic, state.pixiWorld, state.radarLayer); textureSet(state); T.createRadarPool(state);
      state.canvas.addEventListener('webglcontextlost', event => { event.preventDefault(); state.contextLost = true; state.scheduler.cancel(); notice(state, 'WebGL 上下文丢失 · 正在恢复', { blocking: true, error: true }); window.clearTimeout(state.restoreTimer); state.restoreTimer = window.setTimeout(() => notice(state, 'WebGL 恢复超时 · 请刷新页面', { blocking: true, error: true }), 1400); });
      state.canvas.addEventListener('webglcontextrestored', () => { window.clearTimeout(state.restoreTimer); state.contextLost = false; try { notice(state, 'Pixi WebGL · 按需渲染'); state.scheduler.invalidate(FLAGS.ALL, 'context-restored'); } catch (_) { notice(state, 'WebGL 恢复失败 · 请刷新页面', { blocking: true, error: true }); } });
      state.mode = 'pixi'; state.stats.renderer = 'Pixi WebGL'; notice(state, 'Pixi WebGL · 按需渲染'); T.resizeSurface(state); return true;
    } catch (error) { console.warn('Pixi WebGL initialization failed.', error); notice(state, 'WebGL 初始化失败 · 请检查浏览器设置', { blocking: true, error: true }); state.pixiApp = null; return false; }
  };
  T.destroyEntityView = (state, key) => { const view = state.entityViews.get(key); if (!view) return; state.entityViews.delete(key); view.holder.removeFromParent?.(); view.holder.destroy({ children: true, texture: false, baseTexture: false }); };
  const teardown = state => { for (const key of [...state.entityViews.keys()]) T.destroyEntityView(state, key); for (const texture of state.symbolTextures.values()) try { texture.destroy(true); } catch (_) {} state.symbolTextures.clear(); state.radarPool = []; state.radarDomLayer?.remove(); state.radarDomLayer = null; state.radarDomPool = []; if (state.pixiApp) try { state.pixiApp.destroy(true, { children: true, texture: false, baseTexture: false }); } catch (_) {} state.pixiApp = state.pixiWorld = null; state.surfaceGraphic = state.observedGraphic = state.gridGraphic = state.terrainGraphic = state.visionGraphic = state.pathGraphic = null; state.unitLayer = state.radarLayer = null; };
  T.ensureRenderer = state => state.mode !== 'none' || initPixi(state);
  T.resizeSurface = state => { const rect = state.viewport.getBoundingClientRect(); state.size = { w: Math.max(320, Math.round(rect.width || 640)), h: Math.max(300, Math.round(rect.height || 420)) }; if (state.mode === 'pixi' && state.pixiApp) state.pixiApp.renderer.resize(state.size.w, state.size.h); state.scheduler?.invalidate(FLAGS.RESIZE | FLAGS.CAMERA, 'resize'); };
  const visionModels = state => { if (state.layers.vision === 'off') return []; const friendly = [...state.entityModels.values()].filter(m => !m.enemy); if (state.layers.vision === 'all') return friendly; const core = friendly.find(m => m.kind === 'CORE'), selected = state.entityModels.get(state.selectedKey); return [...new Map([core, selected].filter(m => m && !m.enemy).map(m => [m.key, m])).values()]; };
  const gridPixi = state => { const g = state.gridGraphic, b = visibleBounds(state.camera, state.size, 20), step = state.camera.scale >= 18 ? 1 : (state.camera.scale >= 10 ? 2 : (state.camera.scale >= 4 ? 5 : (state.camera.scale >= 1.5 ? 20 : 50))), majorMod = step >= 20 ? (step * 5) : 5; g.clear(); for (let x = Math.floor(b.minX / step) * step; x <= Math.ceil(b.maxX / step) * step; x += step) { const major = x % majorMod === 0; g.lineStyle((major ? 1 : .55) / state.camera.scale, COLOR_NUMBERS.grid, major ? .58 : .24).moveTo(x, b.minY).lineTo(x, b.maxY); } for (let y = Math.floor(b.minY / step) * step; y <= Math.ceil(b.maxY / step) * step; y += step) { const major = y % majorMod === 0; g.lineStyle((major ? 1 : .55) / state.camera.scale, COLOR_NUMBERS.grid, major ? .58 : .24).moveTo(b.minX, y).lineTo(b.maxX, y); } };
  const terrainPixi = state => { const g = state.terrainGraphic, b = visibleBounds(state.camera, state.size, 60), line = 1 / state.camera.scale; g.clear(); for (const cell of state.currentView.obstacles) if (inside(cell, b, 1)) g.lineStyle(line, COLOR_NUMBERS.grid, .85).beginFill(COLOR_NUMBERS.obstacle, .95).drawRect(cell[0] - .34, cell[1] - .34, .68, .68).endFill(); for (const cell of state.currentView.mined) if (inside(cell, b, 1)) g.lineStyle(1 / state.camera.scale, COLOR_NUMBERS.mined, .8).beginFill(COLOR_NUMBERS.mined, .7).drawPolygon([cell[0], cell[1] - .28, cell[0] + .28, cell[1], cell[0], cell[1] + .28, cell[0] - .28, cell[1]]).endFill(); for (const cell of state.currentView.resources) if (inside(cell, b, 1)) g.lineStyle(1.2 / state.camera.scale, COLOR_NUMBERS.resource, 1).beginFill(COLOR_NUMBERS.resource, .86).drawPolygon([cell[0], cell[1] - .34, cell[0] + .34, cell[1], cell[0], cell[1] + .34, cell[0] - .34, cell[1]]).endFill(); for (const cell of (state.currentView.knownResources || [])) if (inside(cell, b, 1)) g.lineStyle(1.2 / state.camera.scale, COLOR_NUMBERS.knownResource, .7).drawPolygon([cell[0], cell[1] - .3, cell[0] + .3, cell[1], cell[0], cell[1] + .3, cell[0] - .3, cell[1]]); const beacon = state.currentView.beacon; if (beacon && inside(beacon.position, b, 1)) { const [x, y] = beacon.position; g.lineStyle(1.6 / state.camera.scale, COLOR_NUMBERS.friendly, .95).drawCircle(x, y, .5); g.beginFill(COLOR_NUMBERS.friendly, .82).drawCircle(x, y, .16).endFill(); } };
  const entityPixi = state => { const b = visibleBounds(state.camera, state.size, 80), visible = new Set(); for (const model of state.entityModels.values()) { if (!inside(model.position, b, 1)) continue; visible.add(model.key); let view = state.entityViews.get(model.key); if (!view) { const holder = new PIXI.Container(), selection = new PIXI.Graphics(), sprite = new PIXI.Sprite(state.symbolTextures.get(model.kind) || state.symbolTextures.get('WORKER')), hp = new PIXI.Graphics(); sprite.anchor.set(.5); sprite.width = sprite.height = 26; holder.addChild(selection, sprite, hp); state.unitLayer.addChild(holder); view = { holder, selection, sprite, hp, label: null, kind: model.kind }; state.entityViews.set(model.key, view); } view.holder.position.set(...model.position); const unitScale = (state.camera.scale < 4 ? clamp(Math.sqrt(state.camera.scale / 4), 0.45, 1) : 1) / state.camera.scale; view.holder.scale.set(unitScale); view.sprite.tint = model.enemy ? COLOR_NUMBERS.enemy : (model.kind === 'CORE' ? COLOR_NUMBERS.resource : COLOR_NUMBERS.friendly); view.holder.alpha = model.data.status === 'BLOCKED' ? .66 : 1; view.selection.clear(); if (model.key === state.selectedKey) view.selection.lineStyle(1.5, COLOR_NUMBERS.text, .9).drawCircle(0, 0, 16); view.hp.clear(); const hp = Number(model.data.hp); const showHp = state.camera.scale >= 4 || model.key === state.selectedKey || model.key === state.hoveredKey; if (showHp && Number.isFinite(hp)) { const ratio = clamp(hp / Math.max(1, Number(model.data.max_hp || KIND_HP[model.kind] || hp)), 0, 1); view.hp.beginFill(COLOR_NUMBERS.enemy, .38).drawRect(-12, 15, 24, 2).endFill().beginFill(COLOR_NUMBERS.friendly, .92).drawRect(-12, 15, 24 * ratio, 2).endFill(); } const labelOn = state.layers.labels && (model.key === state.selectedKey || model.key === state.hoveredKey || state.camera.scale >= 30); if (labelOn && !view.label) { view.label = new PIXI.Text('', { fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Microsoft YaHei", sans-serif', fontSize: 10, fill: 0xffffff }); view.label.position.set(16, -15); view.holder.addChild(view.label); } if (view.label) { view.label.visible = labelOn; if (labelOn) { view.label.tint = view.sprite.tint; view.label.text = `${model.enemy ? '敌方' : KIND_LABELS[model.kind]} ${model.enemy ? '敌' : String(model.data.alias || model.key).slice(-4)}`; } } } for (const key of [...state.entityViews.keys()]) if (!visible.has(key)) T.destroyEntityView(state, key); };
  const renderPixi = (state, flags) => { if (!state.pixiApp || !state.currentView) return; if (flags & (FLAGS.CAMERA | FLAGS.RESIZE)) { state.pixiWorld.position.set(state.size.w / 2 + state.camera.pan.x, state.size.h / 2 + state.camera.pan.y); state.pixiWorld.scale.set(state.camera.scale); state.pixiWorld.pivot.set(...state.camera.anchor); } if (flags & (FLAGS.DATA | FLAGS.LAYERS | FLAGS.RESIZE)) { state.surfaceGraphic.clear().beginFill(state.layers.fog ? COLOR_NUMBERS.bg : COLOR_NUMBERS.observed).drawRect(0, 0, state.size.w, state.size.h).endFill(); state.observedGraphic.clear(); if (state.layers.fog) { state.observedGraphic.beginFill(COLOR_NUMBERS.explored, .85); for (const seg of (state.currentView.exploredSegments || [])) state.observedGraphic.drawRect(seg[0] - .5, seg[2] - .5, seg[1] - seg[0] + 1, 1); state.observedGraphic.endFill(); state.observedGraphic.beginFill(COLOR_NUMBERS.observed, .94); for (const [a, z, y] of state.currentView.observedSegments) state.observedGraphic.drawRect(a - .5, y - .5, z - a + 1, 1); state.observedGraphic.endFill(); } } if (flags & (FLAGS.CAMERA | FLAGS.RESIZE | FLAGS.LAYERS)) gridPixi(state); if (flags & (FLAGS.DATA | FLAGS.CAMERA | FLAGS.RESIZE | FLAGS.LAYERS)) terrainPixi(state); state.visionGraphic.clear(); if (flags & (FLAGS.DATA | FLAGS.SELECTION | FLAGS.LAYERS | FLAGS.CAMERA | FLAGS.RESIZE)) for (const m of visionModels(state)) { const r = Number(m.data.vision_radius); if (r > 0) state.visionGraphic.lineStyle((m.kind === 'CORE' ? 1.35 : 1) / state.camera.scale, m.kind === 'CORE' ? COLOR_NUMBERS.resource : COLOR_NUMBERS.friendly, m.kind === 'CORE' ? .55 : .34).drawPolygon([m.target[0], m.target[1] - r, m.target[0] + r, m.target[1], m.target[0], m.target[1] + r, m.target[0] - r, m.target[1]]); } state.pathGraphic.clear(); const selected = state.entityModels.get(state.selectedKey), target = state.previewTarget || state.lockedTarget; if (selected && target) state.pathGraphic.lineStyle(1.5 / state.camera.scale, COLOR_NUMBERS.resource, .82).moveTo(...selected.position).lineTo(...target).drawCircle(...target, .24); entityPixi(state); if (flags & (FLAGS.DATA | FLAGS.CAMERA | FLAGS.RESIZE)) T.drawRadarPixi(state); state.pixiApp.renderer.render(state.pixiApp.stage); state.stats.objects = 1 + state.entityViews.size * 4; };
  T.renderFrame = (state, flags, reasons, timestamp) => { const started = performance.now(); T.updateAnimations(state, timestamp); try { if (state.mode === 'pixi') renderPixi(state, flags); } catch (error) { console.warn('Tactical map render failed.', error); return notice(state, '地图渲染失败 · 请刷新页面', { blocking: true, error: true }); } if (flags & (FLAGS.CAMERA | FLAGS.RESIZE | FLAGS.LAYERS)) T.updateAxes(state); const done = performance.now(); state.stats.frameMs = done - started; state.stats.frames += 1; state.stats.fps = state.stats.lastRenderedAt ? 1000 / Math.max(1, timestamp - state.stats.lastRenderedAt) : 0; state.stats.lastRenderedAt = timestamp; state.stats.reason = reasons.join(', ') || (flags & FLAGS.ANIMATION ? 'animation' : 'render'); T.updateDebugHud(state); };
})();
